### ISSUE TITLE
In dataset export function please add an option to set the annotation filename

### ISSUE THREAD

**Issue by natanaels12** [openvinotoolkit/datumaro#1185]
For now, the export function does not take argument of annotation filename output. So for example the output of COCO format is always "instances_default.json". Will be nice if there is an option to set this.

**Comment by vinnamkim** [comment]
Hi, @natanaels12 

Thanks for your suggestion on our project. Sorry but my personal thoughts are a little hard on that. This is because there are strict rules to detect COCO data format. Please see the following:
https://github.com/openvinotoolkit/datumaro/blob/b16301058399b866e6c47a90daa88482c727c3e4/src/datumaro/plugins/data_formats/coco/importer.py#L137-L157

The rule to detect the COCO data format is to find JSON files with the naming rule, `{coco_task_name}_{subset_name}.json`. If we give some flexibility on this, for instance, taking any JSON file and investigating its body whether to follow the COCO data format scheme, its performance can be degraded as a trade off to the flexibility. Please let me have some discussions about it among our team.

Thanks you.

**Comment by wonjuleee** [comment]
Thank you for your kind answer @vinnamkim, I will close this issue.
