### ISSUE TITLE
Ram leak when creating dataset

### ISSUE THREAD

**Issue by anwar1997ff** [openvinotoolkit/datumaro#220]
Hello, when using the following example i noticed a memory leak and my system crashes when the number of images is too high.
`dataset = Dataset(categories={
  AnnotationType.label: LabelCategories.from_iterable(['cat', 'dog'])
})
dataset.put(DatasetItem(id=0, image=frame), annotations=[
  Bbox(1, 2, 3, 4, label=0),
]))
dataset.export('test_dataset', 'coco')`

I was wondering what is the best way to handle this type of problem, i am using a combination of the code above and merge every 100 images as a fix. Is there a better way ?

**Comment by zhiltsov-max** [comment]
Hi, please add more details about the situation, include library version info. 

To reduce memory requirements, you can utilize lazy image loading and image cache instead of manual loading. To do this, use `DatasetItem(..., image='path/to/frame/image')` and `DatasetItem(id=0, image=lambda: np.zeros((1, 2, 3)))`. If you're using `Dataset.from_extractors(a, b, c, ...)`, then it can be problematic to avoid high memory consumption on input dataset merging.

**Comment by anwar1997ff** [comment]
Problem was solved using lazy image loading, thanks.
