### ISSUE TITLE
Merge two coco

### ISSUE THREAD

**Issue by kankanzheli** [openvinotoolkit/datumaro#559]
I using 
datum merge dataset1/:image_dir dataset2/:coco dataset3/:coco
to merge two coco datasets. But the result is merge_report.json. How can I get an instance_default.json?

**Comment by zhiltsov-max** [comment]
The command currently produces a Datumaro dataset, so you need to convert it to COCO manually:
```bash
datum convert -i merge_results/ -if datumaro -o merge_coco -f coco -- --reindex=1 # --save-images 
```
There is a PR which introduces such option directly in the `merge` command (#545, discussed in #542), so you can try to use that branch. 

In simple cases (when dataset labels match), consider using `datum patch` instead of merging - this should work faster.

**Comment by kankanzheli** [comment]
I only modify these four parameters during use:

rescaled_ image = cv2.resize(image, (1280, 720)

rescaled_mask = cv2.resize(ann.image, (1280, 720),

dataset = Dataset.import_from('/home/zhaowentao/coco/', 'coco')

dataset.export('/home/zhaowentao/1/', 'coco', save_images=True)

**Comment by kankanzheli** [comment]
Thanks. It is worked.
