### ISSUE TITLE
Patch command example error

### ISSUE THREAD

**Issue by jenhaoyang** [openvinotoolkit/datumaro#602]
for the example **Update the “source1” source in the current project with a dataset:**
```
datum patch -p proj/ --overwrite source1 path/to/dataset2:coco
```
There is two issue
1. for now the default branch name will be source-1 
2. patch command can not correctly locate source-1 folder in the project, result in raising FileExistsError
Reproduce:
```
datum create -o proj 
datum import -p proj -f coco -r annotations/instances_default.json  /home/dataset_merge_exp/a
datum patch -p proj --overwrite source-1 /home/dataset_merge_exp/b:coco
```

if we specify output dir, it will work correctly
```
datum patch -p proj -o proj/source-1 --overwrite source-1 /home/dataset_merge_exp/b:coco
```

**Comment by zhiltsov-max** [comment]
Hi, thank you for reporting the issues.

> 1. for now the default branch name will be source-1

This is the designed behavior, because the word `patch` implies in-place operation by default. Using the `-o/--output-dir` is correct way to save results in another place. Please read the [command description](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/patch/). 

If this logic does not work well, could you describe your use case?

> 2. patch command can not correctly locate source-1 folder in the project, result in raising `FileExistsError`

Thanks, it looks like a Python bug on Windows, actually.
