### ISSUE TITLE
XPath in datumaro

### ISSUE THREAD

**Issue by micahc03** [openvinotoolkit/datumaro#715]
Hi,

I'm currently trying to use XPath to select certain elements from an .xml file. I'm using Python to write datumaro commands, and the .xml file is in CVAT format.

`<box frame="1970"
     keyframe="1"
     occluded="0"
     outside="0"
     xbr="923.38"
     xtl="405.70"
     ybr="3342.50"
     ytl="1732.57"
     z_order="0">
      <attribute name="Event_Type">Syringe_In_Hand</attribute>
      <attribute name="Color">White and Red Border</attribute>
      <attribute name="Drug_Concentration">100</attribute>
      <attribute name="Drug_Name">Sugammadex</attribute>
      <attribute name="Volume">3</attribute>
    </box>`

I want to select annotations (boxes) with "3" inside the @\name="Volume" attribute. I would use a simple contains() function to search for contains(., "3"), and that's what I've used in the past to filter annotations, but this risks mix-ups with the @\name="Drug_Concentration" attribute. 

I currently have a fully-working XPath for the .xml, but when I transfer this path to datumaro and modify it accordingly (mostly just taking off @), it accepts the XPath, yet doesn't output anything as if there were no matches. The XPath is:

`//box[*[@\name="Volume"][contains(.,"3")]]`

I have been testing variants of this path in datumaro, and it seems like the issue lies with *[@\name="Volume"] so far, as I have taken off the [contains(.,"3")] for testing and the path still doesn't output anything. 

I guess the question is, **how do I select an annotation element based off nested attributes properly in datumaro**? The examples provided on the "Filter datasets" page of the user manual are all very simple. I didn't set up the .xml format for this project either.

**Comment by zhiltsov-max** [comment]
Hi. Please keep in mind that original CVAT XML representation is only used during annotation parsing into the internal representation. The `filter` command / API searches for XPath in the XML representation of the parsed data, which is available with `datum filter ... --dry-run`. Each dataset item (an image for the CVAT format) forms a separate XML document. The annotation attributes are included as sub-elements of annotations. For your XPath you should get something close to `/item/annotation[type="bbox" and Volume="3"]` and you'll also need to add `--mode i+a` to filter annotations instead of just images.


This is how items and annotations are represented (from [the `filter` command docs](https://openvinotoolkit.github.io/datumaro/docs/user-manual/command-reference/filter/)):

<details>

```xml
<item>
  <id>290768</id>
  <subset>minival2014</subset>
  <image>
    <width>612</width>
    <height>612</height>
    <depth>3</depth>
  </image>
  <annotation>
    <id>80154</id>
    <type>bbox</type>
    <label_id>39</label_id>
    <x>264.59</x>
    <y>150.25</y>
    <w>11.19</w>
    <h>42.31</h>
    <area>473.87</area>
  </annotation>
  <annotation>
    <id>669839</id>
    <type>bbox</type>
    <label_id>41</label_id>
    <x>163.58</x>
    <y>191.75</y>
    <w>76.98</w>
    <h>73.63</h>
    <area>5668.77</area>
  </annotation>
  ...
</item>
```

</details>

**Comment by micahc03** [comment]
Thanks, got it to work. Thank you very much.
