### ISSUE TITLE
height and width are zero in coco format

### ISSUE THREAD

**Issue by iqraRajpoot** [openvinotoolkit/datumaro#775]
Hi,
i am trying to convert datumaro format (CVAT) to coco format but i am getting zero height and width  instead of getting actual width and height of image. Moreover, i am not even getting segmentation list in the json files. i am attaching screenshots below:
![height_width](https://user-images.githubusercontent.com/35895082/205452480-80698e3f-b57d-4cc9-a589-e35438c35226.png)
![segmentation_list](https://user-images.githubusercontent.com/35895082/205452551-17c1794f-dd9c-4df5-9f10-c50ee8b5bf9e.png)

**Comment by vinnamkim** [comment]
Hi @iqraRajpoot 
Could you upload some of your dataset to somewhere and give a link to us?
It would be helpful to reproduce and investigate your problem by our team.

**Comment by iqraRajpoot** [comment]
Thank you @vinnamkim  for your response, [here](https://drive.google.com/drive/folders/1WlLiCLc3Rx2sd2cP23lhXILxvaOcvkzC?usp=sharing) is the link of dataset and json file.

**Comment by zhiltsov-max** [comment]
Hi, could you please try to export from CVAT with the `Save images` enabled?

![image](https://user-images.githubusercontent.com/13832349/205585643-853b64d5-25e5-4b7e-ac08-ddd52b4bcfc8.png)

**Comment by iqraRajpoot** [comment]
thank you @zhiltsov-max , i am getting this error, would you please help?
UnknownFormatError: Unknown source format 'datumaro'. To make it available, add the corresponding Extractor implementation to the environment, i am attaching screenshot below:
![github_issue](https://user-images.githubusercontent.com/35895082/205599385-146b7e72-73df-41bf-bd7f-f58e1bfbecc7.png)

**Comment by vinnamkim** [comment]
Hi @iqraRajpoot,

To reproduce your problem, I downloaded your dataset and extracted it.
```bash
datumaro_fashionApp
└── datumaro_fashionapp
    ├── annotations
    │   └── default.json
    └── images
        └── default
            ├── female_1.jpg
            ├── female_2.jpg
            ├── female_3.jpg
            ├── female_4.jpg
            ├── female_5.jpg
            ├── male_1.jpg
            ├── male_2.jpg
            ├── male_3.jpg
            ├── male_4.jpg
            └── male_5.jpg
```

Then, on the latest our `develop` branch, I tried to convert it into COCO format by CLI as follows.

```bash
datum convert -i datumaro_fashionApp/datumaro_fashionapp -f coco -o output_coco
```

I could get the output directory.

```bash
output_coco/
├── annotations
│   ├── image_info_default.json
│   └── person_keypoints_default.json
└── images
```

However, `output_coco/annotations/image_info_default.json` has correctly image height and width attributes.
![image](https://user-images.githubusercontent.com/26541465/205781573-d91acd69-c626-4b39-b201-9916bd53d5db.png)

Did you use Python API to convert it rather than CLI command?

> Moreover, i am not even getting segmentation list in the json files. i am attaching screenshots below

In addition, I found that datumaro automatically converts it into COCO keypoint detection format (creating `output_coco/annotations/person_keypoints_default.json`). But it seems that you wanted to convert it into COCO instance segmentation format, Am I right?

**Comment by vinnamkim** [comment]
@iqraRajpoot 

We found that you 1) zero height and width image info and 2) getting empty segmentation points for instance segmentation.

1) Problem 1 can be solved by trying to export from CVAT with the `Save images`.
2) Problem 2 can be solved by annotating objects with `Polygon` rather than `Polyline` in CVAT.

I'm closing this issue because it's been a long time without a response and has little relevance to the Datumaro issue.
