### ISSUE TITLE
raise MediaTypeError("Media type is not an image") datumaro.components.errors.MediaTypeError: Media type is not an image

### ISSUE THREAD

**Issue by snbhanja** [openvinotoolkit/datumaro#899]
Hello, 

I am getting this error when I am trying to convert from Datumaro format to COCO. The Datumaro dataset was downloaded from CVAT. The dataset annotated for segments.

Here is the code I am using,
```python
import datumaro as dm

dataset = dm.Dataset.import_from('datumaro_1stjuly', 'datumaro')

# keep only annotated images
dataset.select(lambda item: len(item.annotations) != 0)

"""
# change dataset labels and corresponding annotations
dataset.transform('remap_labels',
    mapping={
      'cat': 'dog', # rename cat to dog
      'truck': 'car', # rename truck to car
      'person': '', # remove this label
    },
    default='delete') # remove everything else
"""

# iterate over the dataset elements
for item in dataset:
    print(item.id, item.annotations)

# export the resulting dataset in COCO format
dataset.export('output_x3', 'coco', save_images=True)
```

Here is the error,
```bash
Traceback (most recent call last):
  File "/home/snbhanja/ABC/ABC_GRAIN/28thMar2023_v2/reference/convert_datumaro_coco.py", line 24, in <module>
    dataset.export('output_x3', 'coco', save_images=True)
  File "/home/snbhanja/.local/lib/python3.10/site-packages/datumaro/util/scope.py", line 158, in wrapped_func
    ret_val = func(*args, **kwargs)
  File "/home/snbhanja/.local/lib/python3.10/site-packages/datumaro/components/dataset.py", line 1280, in export
    exporter.convert(self, save_dir=save_dir, **exporter_kwargs)
  File "/home/snbhanja/.local/lib/python3.10/site-packages/datumaro/components/exporter.py", line 133, in convert
    return converter.apply()
  File "/home/snbhanja/.local/lib/python3.10/site-packages/datumaro/plugins/data_formats/coco/exporter.py", line 718, in apply
    raise MediaTypeError("Media type is not an image")
datumaro.components.errors.MediaTypeError: Media type is not an image
```

The images are .tif images.
I tried to convert the images to .bmp and also .png formats. I am getting the same error.

Please help.

**Comment by vinnamkim** [comment]
Hi @snbhanja, Thank for your interests on our project!

Can you leave a small subset of your dataset to Github for investigating your problem by our team? or could you check whether a `point_cloud` field exists in the JSON file of your exported dataset? This issue seems similar with the previous one, https://github.com/openvinotoolkit/datumaro/issues/873#issuecomment-1480750868

**Comment by snbhanja** [comment]
@vinnamkim Thank you. Actually, I cannot share the data becuase these are confidential data.
As, you suggested, I did checked the annotation file, the fields "point_cloud" and "media" fields are blank. 
```json
"point_cloud": {
                "path": ""
            },
            "media": {
                "path": ""
            }
```
I also checked the [#873 ](https://github.com/openvinotoolkit/datumaro/issues/873#issuecomment-1480750868) , in one of my dataset I downloded without including images.

But, I created a different dataset, by running cvat locally, these are also tif images. I am facing the same issue here as well and  still even for converting this dataset from datumaro to coco I get the same error.

**Comment by snbhanja** [comment]
@vinnamkim, Thanks, I tried this again.
What happeend was, if I upload images in Cvat directly, it works fine but I pass the reference path of images, then download with with images doesn't work and while conversion this leads to the error.

Conversion works fine now.

**Comment by vinnamkim** [comment]
Hi @snbhanja,

Unfortunately, there has been an issue to export to Datumaro format in CVAT. I enrolled an issue for it to https://github.com/opencv/cvat/issues/5924. Until fixing this from CVAT, could you try to export to other formats rather than Datumaro format and import it using Datumaro? Datumaro can import [other formats](https://openvinotoolkit.github.io/datumaro/docs/formats/) as well.

It might be good to export your dataset to
1. COCO, `dm.Dataset.import_from("<path-to-dataset>", format="coco")` or 
2. CVAT for Images 1.1, `dm.Dataset.import_from(<path-to-dataset>, format="cvat")`.
